### ISSUE TITLE
Side by side magnifier not functioning in other projects

### ISSUE THREAD

**Issue by jcdesigndesk** [AdamRisberg/react-image-magnifiers#11]
The magnifier works fine in the starter project, however it is not functioning within other projects.

I have tried it inside of a create react app based project, as well as a home brewed app that is not based on a boilerplate.

The tests were first made with the image viewer placed within a full page, to test it in context with the other components, next, I created a blank page with nothing but the image viewer component present. 

In both cases, the original image displays, all markup is generated with correct inline styles. Hovering over the image does nothing. It's as though the mouse hover listener is not being registered.

Console is clean, no error messages.

I then created a component that feeds the image viewer with selected images, and placed it within the starter project. It works in that case.

Could it be that a dependency is not being loaded / installed?

Thanks.

**Comment by AdamRisberg** [comment]
I just tried it out in a few different scenarios based on your descriptions and it worked fine for me. One thing I can think of that would cause the behavior you describe is if the image is too small in comparison to the component. 

The image being passed to largeImageSrc (or imageSrc, if you are only using one) needs to be larger (raw image size/resolution, not based on styling) than the component's current display size. If the image is smaller than or equal to the current size of the component, then it's zoom functionality is disabled. It will be displayed as a normal, static image.

The reason for this, is that the component isn't actually "zooming in" on the image. Instead, it is displaying a small version of the image as a preview, and then a full size version on zoom to give the illusion of zooming (but without the quality loss of a real digital zoom). The larger the image, in comparison to the component's display size, the more pronounced the "zoom" is. If the image is too small, instead of showing a broken result, it simply disables the zoom functionality.

Try that out and let me know if that was the issue.

**Comment by AdamRisberg** [comment]
I haven't heard back about this, so I'm going to assume that the provided solution fixed the problem.
