### ISSUE TITLE
Automatically zooms in place using custom layout components

### ISSUE THREAD

**Issue by arso1er** [AdamRisberg/react-image-magnifiers#16]
Hi,

First of all, thanks for this awesome package. 

I'm using custom layout components and I'd like to automatically zoom in place when there's not enough room to display alongside (like with SideBySideMagnifier).

Thanks.

Edit: Actually, I think a zoom in place based on breakpoint specified by user would be even better.

**Comment by AdamRisberg** [comment]
I'll look into this. Unlike the SideBySideMagnifier, the custom layout components are loosely coupled and don't control their own size or positioning. That control is given up to the developer in order to be more flexible. So, right now, I'm not sure if I can add that feature. I'll let you know once I figure it out.

Worst case scenario, if I can't come up with a good way to do it, you may have to add a feature to your app that switches between different magnifier components based on screen size.

**Comment by arso1er** [comment]
OK. Thanks for your answer.

**Comment by AdamRisberg** [comment]
I figured out a way to support both features, an auto in place (for when there isn't enough room) and a min width breakpoint (for activating in place mode based on screen size). 

These features, and the one from your other issue, will be in the next update. I should be posting it in the next 24 hours. I'll let you know when it's up.

**Comment by arso1er** [comment]
Terrific! Thanks for your promptness.

**Comment by AdamRisberg** [comment]
I just published the update to NPM (version 1.3.0). It has both features I mentioned for the custom layout components, as well as some additional styling options. Plus, there are new features added to the SideBySideMagnifier that can make it work similar to Amazon (filling available space). This can be seen on the demo site.

**Comment by arso1er** [comment]
It's working great! 
Thanks.
