### ISSUE TITLE
Make Custom layout components SSR compatible?

### ISSUE THREAD

**Issue by arso1er** [AdamRisberg/react-image-magnifiers#18]
Hi, it's me again.

I tried to use the custom layout components in nextjs and it doesn't work with server side rendering. I took a quick look and found out `transform:translate(NaNpx, NaNpx)` in MagnifierZoom image's style.

Could you take a look at that?

Thanks.

**Comment by AdamRisberg** [comment]
Looks like the issue is that the onload event handler of the zoom image isn't getting called. The component relies on this to get the image size for calculations. What I didn't account for, is that in SSR the image can load before the javascript does. Which means the onload event can be fired before my event handler is added.

I should have have the fix released later tonight.

**Comment by AdamRisberg** [comment]
I just released a fix, version 1.3.1. Aside from the problem you found, I also found and fixed a few potential issues that could have arose where the server side and client side versions of the DOM wouldn't match during hydration.

**Comment by arso1er** [comment]
I updated the package and it's working with ssr now.

Thanks again for your hard work.
