### ISSUE TITLE
Need a way to attach preview to external div.

### ISSUE THREAD

**Issue by creatorisback** [AdamRisberg/react-image-magnifiers#8]
I'm using side by side image preview and it's a boundation from the design that I cannot remove overflow hidden from the parent.
Is there any way I can attach preview to external div by using it's id or something?

**Comment by AdamRisberg** [comment]
No, there is currently no way to render one of the views into an external div. Also, some internal styling (like the overflow hidden on the zoomed image’s parent div) cannot be overwritten because it is necessary for the component to function properly in its current state.

If you let me know exactly what you are trying to achieve, I can try to either come up with a solution for this component or even add a new component to the collection that handles it. For example, do you need the zoomed image to be larger or a different shape than the initial preview image? In a different location?

**Comment by creatorisback** [comment]
@AdamRisberg 
Yes, I want to show zoom preview at a different location, let me know you an example of what I'm trying to achieve.
[kindly visit this link](https://www.flipkart.com/philips-10000-mah-power-bank-dlp1710cv-97-universal-pack/p/itmffex2wpryd8ta?pid=PWBFFEX2SFFKB9KP&lid=LSTPWBFFEX2SFFKB9KPLSQPWL&marketplace=FLIPKART&spotlightTagId=BestsellerId_tyy&srno=b_1_1&otracker=hp_omu_Deals%2Bof%2Bthe%2BDay_2_2.dealCard.OMU_CE7DPNHNIXBZ_2&otracker1=hp_omu_PINNED_neo%2Fmerchandising_Deals%2Bof%2Bthe%2BDay_NA_dealCard_cc_2_NA_view-all_2&fm=neo%2Fmerchandising&iid=ac16c338-c644-4d05-988f-59021c2ff952.PWBFFEX2SFFKB9KP.SEARCH&ppt=browse&ppn=browse&ssid=npxrr3wsxc0000001569290743952)
I'm just trying to implement the exact same functionality.

**Comment by AdamRisberg** [comment]
I'll look into it and see if I can come up with a way to support this functionality.

**Comment by AdamRisberg** [comment]
As of version 1.2.0, I added three new components for creating a magnifier with a custom layout. They allow you to have separate components for the preview and zoom views that you can size, position, and style however you want. Check the README for more info.
